name: Docker Image CI

on: 
  workflow_dispatch:
    inputs:
      steamLogin:
        description: 'Steam Login'     
        required: true
        default: 'user password 2fa-code'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: inttheory/deadmatter-server
          docker-build-args: "--build-arg STEAM_LOGIN=${{ github.event.inputs.steamLogin }}"
